### ISSUE TITLE
Tracking issue of endpoint APIs

### ISSUE THREAD

**Issue by ubnt-intrepid** [finchers-rs/finchers#42]
### Tasks
- [x] Remove unused endpoints (#46, #48)
- [x] Change the return type of `Endpoint::apply` to `Option<Self::Task>` (https://github.com/finchers-rs/finchers/issues/44#issuecomment-353537499, #51)
  - [x] Remove `EndpointError` and add `NotFound` represents that the request does not match to all endpoints
- [x] Replace the trait bound `Endpoint` to `IntoEndpoint` in the definition of `Endpoint` (#53)
- [x] Remove unnecessary type parameters from combinators (#53)
- [x] Fixup `EndpointContext`
  - [x] define ~~`PathSegmentIter`~~ `Segments` (#48)
  - [x] ~~defer the parsing of query string~~ (#48)
- [x] Fix privacies (#54)
- [x] ~~Add support for multiple path segments (#47)~~ moved to #82 
- [x] ~~Introduce `FromSegments` trait  and code generation (#39)~~ moved to #82
