### ISSUE TITLE
Cookie management

### ISSUE THREAD

**Issue by ubnt-intrepid** [finchers-rs/finchers#65]
いくつかの機能（主にセッション管理）を実現するためには Cookie の扱いが必要となる。これは多くのエンドポイントにまたがり必要となるため組み込み機能として提供する。

### Tasks
- [x] Cookie の読み込み + 書き込み (#70)
- [x] `CookieJar` のカプセル化
- [x] PrivateJar ~~, SignedJar~~ 対応
- [x] 最適化（`Cookie` 解析の遅延など）

**Comment by ubnt-intrepid** [comment]
```rust
impl TaskContext {
    fn cookie(&mut self) -> &mut CookieJar { ... }
}

trait Responder {
    fn cookies(&self, cookies: &mut CookieJar) {}
}
```
